website: 'http://serlib.eu/'
description: >-
  SerLib is a fast, and easy to use serialisation c++ library. The whole library
  is designed with performance, and ease of use in mind.
keywords:
  - C++
  - Serialisation
  - easy
  - fast
license: MIT
authors:
  - website: 'https://zefiros.eu/'
    email: m.vanduijn@zefiros.eu
    name: Mick van Duijn
  - website: 'https://zefiros.eu/'
    email: p.e.visscher@zefiros.eu
    name: Paul Visscher
  - website: 'https://zefiros.eu/'
    email: k.m.visscher@zefiros.eu
    name: Koen Visscher
development:
  modules:
    - name: Zefiros-Software/Defaults
      version: '@head'
