description: 'SerLib is a fast, and easy to use serialisation c++ library. The whole library is designed with performance, and ease of use in mind.'
keywords:
  - C++
  - Serialisation
  - easy
  - fast
website: 'http://serlib.eu/'
license: MIT
authors:
  - name: Mick van Duijn
    email: m.vanduijn@zefiros.eu
    website: 'https://zefiros.eu/'
  - name: Paul Visscher
    email: p.e.visscher@zefiros.eu
    website: 'https://zefiros.eu/'
  - name: Koen Visscher
    email: k.m.visscher@zefiros.eu
    website: 'https://zefiros.eu/'
development:
  modules:
    - name: Zefiros-Software/Zefiros-Defaults
      version: '@head'